import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'models/cart_item.dart'; // For CartItemAdapter
import 'services/cart_service.dart'; // For opening the cart box
import 'screens/home_screen.dart';
import 'screens/account_screen.dart';
import 'screens/cart_screen.dart';
import 'screens/menu_screen.dart';
import 'screens/settings_screen.dart';
// import 'package:path_provider/path_provider.dart' as path_provider; // If needed for specific Hive setup

// 商品モデルクラス
class Product {
  final String id;
  final String name;
  final int price;
  final String imageUrl;

  Product({
    required this.id,
    required this.name,
    required this.price,
    required this.imageUrl,
  });
}

// モック商品データ
final List<Product> mockProducts = [
  Product(
    id: '1',
    name: 'スニーカー',
    price: 5980,
    imageUrl: 'https://picsum.photos/id/21/200/200',
  ),
  Product(
    id: '2',
    name: 'ヘッドホン',
    price: 12800,
    imageUrl: 'https://picsum.photos/id/27/200/200',
  ),
  Product(
    id: '3',
    name: '腕時計',
    price: 32000,
    imageUrl: 'https://picsum.photos/id/111/200/200',
  ),
  Product(
    id: '4',
    name: 'バックパック',
    price: 8500,
    imageUrl: 'https://picsum.photos/id/83/200/200',
  ),
  Product(
    id: '5',
    name: 'サングラス',
    price: 6200,
    imageUrl: 'https://picsum.photos/id/20/200/200',
  ),
  Product(
    id: '6',
    name: 'スマートウォッチ',
    price: 24800,
    imageUrl: 'https://picsum.photos/id/96/200/200',
  ),
  Product(
    id: '7',
    name: 'ノートパソコン',
    price: 89800,
    imageUrl: 'https://picsum.photos/id/48/200/200',
  ),
  Product(
    id: '8',
    name: 'ワイヤレスイヤホン',
    price: 15400,
    imageUrl: 'https://picsum.photos/id/127/200/200',
  ),
  Product(
    id: '9',
    name: 'デジタルカメラ',
    price: 42500,
    imageUrl: 'https://picsum.photos/id/250/200/200',
  ),
  Product(
    id: '10',
    name: 'スマートフォン',
    price: 78000,
    imageUrl: 'https://picsum.photos/id/160/200/200',
  ),
];

void main() async {
  // Make main async
  WidgetsFlutterBinding.ensureInitialized(); // Ensure bindings are initialized

  // Initialize Hive
  await Hive.initFlutter();

  // Register Adapters
  // The CartItemAdapter class will be generated by build_runner
  Hive.registerAdapter(CartItemAdapter());

  // Open the Hive box for the cart
  // This instance is just for opening the box.
  // The CartNotifier will use its own instance via the cartServiceProvider.
  await CartService().openCartBox();

  runApp(
    const ProviderScope(
      // Wrap with ProviderScope
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter App', // Or your app's title
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MainScreen(), // Set MainScreen as home
    );
  }
}

class MainScreen extends StatefulWidget {
  const MainScreen({super.key});

  @override
  State<MainScreen> createState() => _MainScreenState();
}

class _MainScreenState extends State<MainScreen> {
  int _selectedIndex = 0; // Default to Home screen

  static final List<Widget> _widgetOptions = <Widget>[
    HomeScreen(),
    const AccountScreen(),
    const CartScreen(),
    const MenuScreen(),
    const SettingsScreen(),
  ];

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // appBar: AppBar( // Optional: A global AppBar
      //   title: const Text('App Name'),
      // ),
      body: Center(
        child: _widgetOptions.elementAt(_selectedIndex),
      ),
      bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.account_circle),
            label: 'Account',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.shopping_cart),
            label: 'Cart',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.menu),
            label: 'Menu',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            label: 'Settings',
          ),
        ],
        currentIndex: _selectedIndex,
        selectedItemColor: Colors.amber[800], // Example color
        unselectedItemColor: Colors.grey, // Ensure unselected items are visible
        onTap: _onItemTapped,
        type: BottomNavigationBarType.fixed, // To ensure all labels are shown
      ),
    );
  }
}

// Removed HomePage and CheckoutPage as they are not part of this task's scope
// and will be replaced or integrated differently later.
